name: IT Blog
markdown: kramdown
kramdown:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: rouge
permalink: pretty

# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
highlighter: rouge
lsi: false

redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap
